/**
 * A Swing panel that displays all decks in the Trading Card Inventory System using a scrollable grid layout.
 * Users can create new decks using the styled "Create Deck" button, while existing decks
 * are shown in a 3-column layout with individual panels generated by {@link DeckViewHelper}.
 * This panel is styled consistently with the rest of the GUI and powered by {@link DeckController}
 * for handling deck-related actions.
 * 
 * @version 2.0  
 * @author Theodore Garcia  
 * @author Ronin Zerna  
 */

package view;

import model.*;
import controller.*;
import javax.swing.*;
import java.awt.*;

/**
 * A panel responsible for displaying all decks in the trading card inventory system.
 * Provides functionality to create decks and dynamically refresh deck displays.
 */
public class DeckPanel extends JPanel {
    private JPanel deckGrid;
    private DeckController controller;
    private DeckViewHelper helper;

    /**
     * Constructs a new {@code DeckPanel} for displaying and managing decks.
     *
     * @param tcis      the trading card inventory system instance
     * @param parentGui the main GUI frame
     */
    public DeckPanel(TradingCardInventorySystem tcis, TCISGUI parentGui) {
        this.controller = new DeckController(tcis, parentGui);
        this.helper = new DeckViewHelper();
        setLayout(new BorderLayout());
        setBackground(new Color(245, 245, 250));

        // Styled Create Deck Button
        JButton createDeckBtn = new JButton("Create Deck");
        createDeckBtn.setFont(FontManager.NEXA_H.deriveFont(22f));
        createDeckBtn.setBackground(new Color(100, 140, 240));
        createDeckBtn.setForeground(Color.WHITE);
        createDeckBtn.setFocusPainted(false);
        createDeckBtn.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        createDeckBtn.addActionListener(e -> DeckViewHelper.openCreateDeckDialog(tcis, parentGui));

        // Top Bar Styling
        JPanel topBar = new JPanel();
        topBar.setBackground(new Color(245, 245, 250));
        topBar.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topBar.setLayout(new FlowLayout(FlowLayout.LEFT));
        topBar.add(createDeckBtn);

        // Deck Grid (3 per row)
        deckGrid = new JPanel(new GridBagLayout());
        deckGrid.setBackground(new Color(245, 245, 250));
        deckGrid.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JScrollPane scrollPane = new JScrollPane(deckGrid);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        add(topBar, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);

        refreshDecks(tcis, parentGui);
    }

    /**
     * Refreshes the displayed deck grid by clearing and repopulating with updated deck data.
     *
     * @param tcis the trading card inventory system
     * @param gui  the GUI instance (for callbacks)
     */
    public void refreshDecks(TradingCardInventorySystem tcis, TCISGUI gui) {
        deckGrid.removeAll();

        int col = 0, row = 0;
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.NORTHWEST;

        for (Deck deck : tcis.getDecks()) {
            JPanel panel = helper.createContainerPanel(deck, tcis, controller);
            gbc.gridx = col;
            gbc.gridy = row;
            deckGrid.add(panel, gbc);

            col++;
            if (col >= 3) {
                col = 0;
                row++;
            }
        }

        deckGrid.revalidate();
        deckGrid.repaint();
    }
}
